repos:
- repo: https://github.com/ambv/black
  rev: 18.9b0
  hooks:
  - id: black
    exclude: docopt.py
    language_version: python3.6
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.5
  hooks:
  - id: flake8
- repo: https://github.com/asottile/blacken-docs
  rev: v0.3.0
  hooks:
  - id: blacken-docs
    additional_dependencies: [black==18.9b0]

